"use client"

import { useEffect, useContext } from 'react';
import { store } from '@/app/faceholder/context/store.js';

//import { getThisPersonDoesNotExist } from './utils/getThisPersonDoesNotExist';
// import { getFaces } from './utils/getFaces';

import { Header, Main, Footer, Wrapper } from '@/components';
import { Gallery } from '@/app/faceholder/components/Gallery';

import { Grid, Row, Column } from '@/common-ui';


import { ImageItem } from '@/components/ImageItem';
import { Link } from '@/common-ui/Link';
// import { Link } from './components/Link';
// import { BumperSection } from './components/BumperSection';

import { getFacesFromGlitch } from './api/getFacesFromGlitch';


import './styles.scss';


export default function Home() {
  const { state, dispatch } = useContext(store);


  // const [faceholders, setFaceholers] = useState(null);
  // const { isSuccess, setSuccess } = useState(false);

  
  const { assets, assetsAmount, refresh } = state;

  const getAssets = async () => {
    // UseCallback function here
    await getFacesFromGlitch(assetsAmount).then((images) => {
      console.log(images);
      dispatch({ type: 'upload assets', value: images });
      dispatch({
        type: 'refresh',
        value: false
      });
    });
  };

  // Investigating if data is pushed to the state
  useEffect(() => {
    
    if (refresh) getAssets();

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refresh]);

  return (
    <>
      <Header appName="Faceholder" />
      <LeadSpace />
      <Main>
        {/* <BrowsePhotos assets={assets} /> */}
        <Gallery data={assets} />
        <About />
      </Main>
      <Footer appName="Faceholder" />
    </>
  );
}

const LeadSpace = () => {
  return (
    <section>
      <Wrapper className="Leadspace">
        <div className="Leadspace-container column">
          <h1 className="responsive-heading-06 monoblock">Welcome to Faceholder</h1>
          <p className="responsive-paragraph-03 monoblock">Explore and download cool unreal faces</p>
          <div className="responsive-paragraph-03 monoblock ">↓</div>
        </div>
      </Wrapper>
    </section>
  )
}

const BrowsePhotos = ({ assets }) => {
  return(
    <section id="browse" className="BrowsePhotos">
      <Grid>
        <Row>
          <ImageItem source={{ url: 'https://ozgrozer.github.io/100k-faces/0/3/003443.jpg?q=50' }} />
        </Row>
      </Grid>
      {/* <Gallery data={assets} /> */}
    </section>
  );
}

const About = () => {
  const links = {
    nvidia: 'https://github.com/NVlabs/stylegan',
    stylegan: 'https://en.wikipedia.org/wiki/StyleGAN',
    faces: 'https://en.wikipedia.org/wiki/Human_image_synthesis'
  };
  return(
    <Grid id="about" className="About">
      <section>
        

        <div className="section-container">
          <h2>About</h2>
          {/* <div className="content column">
            <p className="responsive-paragraph-02">
              Faceholder was created to browse portraits of{' '}
              <Link href={links.faces}>fake human faces</Link>, generated by AI
              using <Link href={links.stylegan}>StyleGan2</Link> made by{' '}
              <Link href={links.nvidia}>Nvidia</Link>.
            </p>
          </div> */}
          <Row>
            <Column col={6} colSm={4} colMd={4} colLg={6}>
              <p className="responsive-paragraph-02">
                Faceholder was created to browse portraits of{' '}
                <Link href={links.faces}>fake human faces</Link>, generated by AI
                using <Link href={links.stylegan}>StyleGan2</Link> made by{' '}
                <Link href={links.nvidia}>Nvidia</Link>.
              </p>
            </Column>
          </Row>
        </div>

      </section>
    </Grid>
  );
};